projects:
  project:
    schema: http://localhost:8000/___graphql
    documents: src/queries/**/*.graphql
    extensions:
      endpoints:
        default:
          url: http://localhost:8000/___graphql
