name: "Autodeploy"

on:
  schedule:
    - cron: "30 9 * * *"

jobs:
  deploy:
    name: "deploy to gatsby"
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.GATSBY_BUILD_HOOK }}